### ISSUE TITLE
levmar fails to compile

### ISSUE THREAD

**Issue by mneilly** [starseeker/meshlab#6]
FYI - this fails to compile on Debian 8 using liblapack3 (3.5.0-4) with the following error:

```
[100%] Linking C executable lmdemo
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libf2c.so: undefined reference to `MAIN__'
collect2: error: ld returned 1 exit status
CMakeFiles/lmdemo.dir/build.make:95: recipe for target 'lmdemo' failed
make[2]: *** [lmdemo] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/lmdemo.dir/all' failed
make[1]: *** [CMakeFiles/lmdemo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

The Levmar FAQ indicates a couple of solutions:
http://users.ics.forth.gr/~lourakis/levmar/faq.html#Q26
